version: '3'
services:
  netdata:
    image: netdata/netdata
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    deploy:
      mode: global

  dashboard:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./dashboard.html:/usr/share/nginx/html/index.html:ro
    ports:
      - 80:80
      - 443:443
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

volumes:
  netdataconfig:
  netdatalib:
  netdatacache: